# Generated by Django 5.1.1 on 2024-11-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAgent',
            fields=[
                ('dispatch_agent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('deliveries', models.JSONField()),
                ('products', models.JSONField()),
                ('orders', models.JSONField()),
            ],
            options={
                'db_table': 'dispatchagent',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('products', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('address', models.JSONField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
                ('enquiry_id', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=50)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('payment_source', models.CharField(max_length=100)),
                ('time_to_deliver', models.DurationField()),
                ('dispatch_agent_id', models.CharField(max_length=100)),
                ('calling_agent_id', models.CharField(max_length=100)),
                ('team_leader_id', models.CharField(max_length=100)),
                ('manager_id', models.CharField(max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('delivery_company', models.CharField(blank=True, max_length=100, null=True)),
                ('accounts_approval', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.DeleteModel(
            name='Dispatch',
        ),
        migrations.RenameField(
            model_name='callingagent',
            old_name='agent_id',
            new_name='calling_agent_id',
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='interested',
            field=models.CharField(choices=[('interested', 'interested'), ('not-interested', 'not-interested')], max_length=100),
        ),
    ]
