# Generated by Django 5.1.1 on 2024-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_dispatchagent_order_delete_dispatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processhead',
            fields=[
                ('process_head_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('process_head_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('process_name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('login_times', models.JSONField()),
                ('permissions', models.JSONField()),
                ('department', models.CharField(default='Calling', max_length=50)),
                ('calling_agents', models.JSONField()),
                ('targets', models.JSONField()),
                ('conversion_rate', models.JSONField()),
                ('failed_deals', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='teamleader',
            fields=[
                ('team_leader_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_leader_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('login_times', models.JSONField()),
                ('permissions', models.JSONField()),
                ('department', models.CharField(default='Calling', max_length=50)),
                ('calling_agents', models.JSONField()),
                ('targets', models.JSONField()),
                ('conversion_rate', models.JSONField()),
                ('failed_deals', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='callingagent',
            name='calling_agent_name',
            field=models.CharField(default='not defined', max_length=30),
        ),
        migrations.AddField(
            model_name='callingagent',
            name='orders',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='callingagent',
            name='password',
            field=models.CharField(default='krmcrm123', max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchagent',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
