# Generated by Django 5.1.1 on 2024-11-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_processhead_teamleader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callingagent',
            old_name='calling_agent_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='dispatchagent',
            old_name='dispatch_agent_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='processhead',
            old_name='process_head_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='teamleader',
            old_name='team_leader_id',
            new_name='user_id',
        ),
    ]
