# Generated by Django 5.1.1 on 2024-11-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_rename_calling_agent_id_callingagent_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingagent',
            name='enquiry',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='callingagent',
            name='profile',
            field=models.CharField(default='callingagent'),
        ),
        migrations.AddField(
            model_name='dispatchagent',
            name='profile',
            field=models.CharField(default='dispatchagent', max_length=30),
        ),
        migrations.AddField(
            model_name='processhead',
            name='profile',
            field=models.CharField(default='processhead'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='profile',
            field=models.CharField(default='teamleader'),
        ),
    ]
