# Generated by Django 5.1.1 on 2024-11-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_callingagent_enquiry_callingagent_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingagent',
            name='login_times',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='permissions',
            field=models.JSONField(null=True),
        ),
    ]
