# Generated by Django 5.1.1 on 2024-11-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_callingagent_attendance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processhead',
            table='processhead',
        ),
        migrations.AlterModelTable(
            name='teamleader',
            table='teamleader',
        ),
    ]
