# Generated by Django 5.1.1 on 2024-11-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_hospital_beds_alter_hospital_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='countries_available',
            new_name='countries',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='diseases',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='strength',
            new_name='major_minor',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
