# Generated by Django 5.1.1 on 2024-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_rename_countries_available_medicine_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
