# Generated by Django 5.1.1 on 2024-11-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_alter_callingagent_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingagent',
            name='attendance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='conversion_rate',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='enquiry',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='failed_deals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='interactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='login_times',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='manager',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='orders',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='targets',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='team_leader',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
