# Generated by Django 5.1.1 on 2024-11-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_dme_callingagent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme',
            name='counter',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
