# Generated by Django 5.1.1 on 2024-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_dme_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme',
            name='attendance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dme',
            name='profile',
            field=models.CharField(default='dme', max_length=50),
        ),
    ]
