# Generated by Django 5.1.1 on 2024-11-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_dme_attendance_alter_dme_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dme',
        ),
    ]
