# Generated by Django 5.1.1 on 2024-11-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_dme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme',
            name='counter',
        ),
    ]
