# Generated by Django 5.1.1 on 2024-11-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_remove_dme_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callingagent',
            old_name='calling_agent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dme',
            old_name='dme_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='processhead',
            old_name='process_head_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teamleader',
            old_name='team_leader_name',
            new_name='name',
        ),
    ]
