# Generated by Django 5.1.1 on 2024-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_rename_calling_agent_name_callingagent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdlead',
            name='contacted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
