# Generated by Django 5.1.1 on 2024-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_jdlead_contacted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdlead',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='brancharea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='branchpin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='contacted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='dncmobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='dncphone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='interested',
            field=models.CharField(blank=True, choices=[('interested', 'interested'), ('not-interested', 'not-interested')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='parentid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jdlead',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
