# Generated by Django 5.1.1 on 2024-11-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0026_rename_username_superadmin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='profile',
            field=models.CharField(default='superadmin'),
        ),
    ]
