# Generated by Django 5.1.1 on 2024-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0027_superadmin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='agent',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='app',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='conversion_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='demographics',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='failed_deals',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='interactions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='landing_page',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='patient_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='products',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='retention',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_ad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_browser',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_campaign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_device',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_others',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='utm_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='visit_history',
            field=models.JSONField(null=True),
        ),
    ]
