# Generated by Django 5.1.1 on 2024-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0029_alter_enquiry_date_alter_enquiry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='counter',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
