# Generated by Django 5.1.1 on 2024-11-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0030_enquiry_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
