# Generated by Django 5.1.1 on 2024-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0032_enquiry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='disease_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='disease',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], max_length=255, null=True),
        ),
    ]
