# Generated by Django 5.1.1 on 2024-11-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_enquiry_disease_code_enquiry_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='last_name',
        ),
    ]
