# Generated by Django 5.1.1 on 2024-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_alter_enquiry_disease_alter_enquiry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='disease',
            field=models.CharField(choices=[('Kidney', 'Kidney'), ('Cancer', 'Cancer'), ('Others', 'Others')], default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
