# Generated by Django 5.1.1 on 2024-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0037_alter_enquiry_disease_alter_enquiry_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme',
            name='sources',
        ),
        migrations.AddField(
            model_name='source',
            name='dmes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='disease',
            field=models.CharField(choices=[('Kidney', 'Kidney'), ('Cancer', 'Cancer'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
