# Generated by Django 5.1.1 on 2024-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0039_rename_interactions_enquiry_dme_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='interactions',
            field=models.JSONField(null=True),
        ),
    ]
