# Generated by Django 5.1.1 on 2024-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0040_enquiry_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.CharField(null=True),
        ),
    ]
