# Generated by Django 4.2.7 on 2024-12-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0042_enquiry_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='dme',
            field=models.CharField(null=True),
        ),
    ]
