# Generated by Django 4.2.7 on 2024-12-04 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0043_enquiry_dme'),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Other', 'Other')], max_length=100)),
                ('disease', models.JSONField()),
                ('type', models.CharField(choices=[('Aquisition', 'Aquisition'), ('Retention', 'Retention')], max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
