# Generated by Django 4.2.7 on 2024-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0044_process_enquiry_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processhead',
            name='calling_agents',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='calling_agents',
        ),
        migrations.AddField(
            model_name='teamleader',
            name='process_head',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callingagent',
            name='team_leader',
            field=models.CharField(blank=True, null=True),
        ),
    ]
