# Generated by Django 4.2.7 on 2024-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0045_remove_processhead_calling_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingagent',
            name='process_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='process_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
