# Generated by Django 4.2.7 on 2024-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0046_callingagent_process_name_teamleader_process_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhead',
            name='process_name',
            field=models.JSONField(),
        ),
    ]
