# Generated by Django 4.2.7 on 2024-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0047_alter_processhead_process_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingagent',
            name='process_name',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='process_name',
            field=models.JSONField(),
        ),
    ]
