# Generated by Django 4.2.7 on 2024-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0049_alter_callingagent_process_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhead',
            name='process_name',
            field=models.JSONField(null=True),
        ),
    ]
