# Generated by Django 4.2.7 on 2024-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0050_alter_processhead_process_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='country',
        ),
        migrations.RemoveField(
            model_name='source',
            name='disease',
        ),
        migrations.AddField(
            model_name='process',
            name='sub_disease',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='process_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='disease',
            field=models.CharField(null=True),
        ),
    ]
