# Generated by Django 4.2.7 on 2024-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0051_remove_source_country_remove_source_disease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sub_disease', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.AddField(
            model_name='callingagent',
            name='process_head',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
