# Generated by Django 4.2.7 on 2024-12-07 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0054_enquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingagent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
