# Generated by Django 4.2.7 on 2024-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0055_callingagent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme',
            name='counter',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
