# Generated by Django 4.2.7 on 2024-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0058_processhead_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='major_minor',
        ),
        migrations.AddField(
            model_name='disease',
            name='medicines',
            field=models.JSONField(null=True),
        ),
    ]
