# Generated by Django 4.2.7 on 2024-12-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0059_remove_medicine_major_minor_disease_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='disease',
        ),
    ]
