# Generated by Django 4.2.7 on 2024-12-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0060_remove_medicine_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='disease',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sub_disease',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
