# Generated by Django 4.2.7 on 2024-12-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0065_enquiry_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='callingagent',
            field=models.CharField(null=True),
        ),
    ]
