# Generated by Django 4.2.7 on 2024-12-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0066_enquiry_callingagent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='callingagent',
            new_name='calling_agent',
        ),
    ]
