# Generated by Django 4.2.7 on 2024-12-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0067_rename_callingagent_enquiry_calling_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('notification_name', models.CharField(null=True)),
                ('level', models.CharField(choices=[('General', 'General'), ('Important', 'Important'), ('Critical', 'Critical')])),
                ('department', models.CharField(null=True)),
                ('users', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('readby', models.JSONField(null=True)),
            ],
        ),
    ]
