# Generated by Django 4.2.7 on 2024-12-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0070_rename_readby_notification_unreadby'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
