# Generated by Django 4.2.7 on 2024-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0071_alter_notification_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='knowledgebank',
            fields=[
                ('knowledge_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('topic', models.CharField()),
                ('user_id', models.CharField()),
                ('department', models.CharField()),
                ('answer', models.TextField()),
                ('hashtags', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
