# Generated by Django 4.2.7 on 2024-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0072_knowledgebank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebank',
            name='hashtags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebank',
            name='topic',
            field=models.CharField(null=True),
        ),
        migrations.AlterModelTable(
            name='knowledgebank',
            table='knowledgebank',
        ),
    ]
