# Generated by Django 4.2.7 on 2025-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0074_rename_department_knowledgebank_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('user_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField()),
            ],
            options={
                'db_table': 'hr',
            },
        ),
        migrations.CreateModel(
            name='kra',
            fields=[
                ('kras', models.JSONField()),
                ('profile', models.CharField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kra',
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('profile', models.CharField(null=True)),
                ('users', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.CharField()),
                ('ended_at', models.CharField()),
                ('description', models.CharField()),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')])),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
        migrations.AddField(
            model_name='callingagent',
            name='kras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dispatchagent',
            name='kras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dme',
            name='kras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='processhead',
            name='kras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='kras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
