# Generated by Django 4.2.7 on 2025-01-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0076_remove_timetable_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='disposition',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('dispositions', models.JSONField(default=[], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disposition',
            },
        ),
    ]
