# Generated by Django 4.2.7 on 2025-01-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0077_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='dispositions',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable',
            field=models.JSONField(default=dict),
        ),
    ]
