# Generated by Django 4.2.7 on 2025-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0078_alter_disposition_dispositions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='id',
            field=models.CharField(default='id', primary_key=True, serialize=False, unique=True),
        ),
    ]
