# Generated by Django 4.2.7 on 2025-01-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0079_alter_disposition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='users',
        ),
    ]
