# Generated by Django 4.2.7 on 2025-01-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0080_remove_timetable_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
