# Generated by Django 5.1.1 on 2024-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dme',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='krmcrm123', max_length=255)),
                ('dme_name', models.CharField(max_length=30, null=True)),
                ('sources', models.JSONField(blank=True, default=dict, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enquiry', models.JSONField(blank=True, default=dict, null=True)),
                ('color', models.CharField(blank=True, choices=[('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], max_length=100, null=True)),
                ('login_times', models.JSONField(blank=True, default=dict, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict, null=True)),
                ('department', models.CharField(default='Digital', max_length=50)),
                ('attendance', models.JSONField(blank=True, default=dict, null=True)),
                ('profile', models.CharField(default='dme', max_length=50)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'dme',
            },
        ),
    ]
