# Generated by Django 5.1.1 on 2024-11-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dme',
        ),
    ]
